// <auto-generated />
using System;
using Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entity.Migrations
{
    [DbContext(typeof(PortfolioContext))]
    partial class PortfolioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Entity.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "KZ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ES"
                        });
                });

            modelBuilder.Entity("Entity.Entity.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Currencys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PLN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DKK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AUD"
                        },
                        new
                        {
                            Id = 4,
                            Name = "USD"
                        },
                        new
                        {
                            Id = 5,
                            Name = "XCD"
                        },
                        new
                        {
                            Id = 6,
                            Name = "MXV"
                        });
                });

            modelBuilder.Entity("Entity.Entity.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurrencyId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("ISIN");

                    b.Property<float>("MarketValue");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Entity.Entity.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<int>("CurrencyId");

                    b.Property<string>("ISIN");

                    b.Property<float>("MarketValue");

                    b.Property<string>("Name");

                    b.Property<int>("PortfolioId");

                    b.Property<float>("SharePercentage");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TypeId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Entity.Entity.PositionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PositionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fund"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Share"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bond"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Entity.Entity.Portfolio", b =>
                {
                    b.HasOne("Entity.Entity.Currency", "Currency")
                        .WithMany("Portfolio")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Entity.Entity.Position", b =>
                {
                    b.HasOne("Entity.Entity.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entity.Entity.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entity.Entity.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entity.Entity.PositionType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
